// Code generated by protoc-gen-go.
// source: promo.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	promo.proto

It has these top-level messages:
	Promo
*/
package main

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Promo struct {
	Id               *int32              `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string             `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	BaseCode         *string             `protobuf:"bytes,3,req,name=base_code" json:"base_code,omitempty"`
	IsGlobal         *int32              `protobuf:"varint,4,req,name=is_global" json:"is_global,omitempty"`
	Rules            []*Promo_Rule       `protobuf:"bytes,5,rep,name=rules" json:"rules,omitempty"`
	Timewindows      []*Promo_TimeWindow `protobuf:"bytes,6,rep,name=timewindows" json:"timewindows,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Promo) Reset()         { *m = Promo{} }
func (m *Promo) String() string { return proto.CompactTextString(m) }
func (*Promo) ProtoMessage()    {}

func (m *Promo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Promo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Promo) GetBaseCode() string {
	if m != nil && m.BaseCode != nil {
		return *m.BaseCode
	}
	return ""
}

func (m *Promo) GetIsGlobal() int32 {
	if m != nil && m.IsGlobal != nil {
		return *m.IsGlobal
	}
	return 0
}

func (m *Promo) GetRules() []*Promo_Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *Promo) GetTimewindows() []*Promo_TimeWindow {
	if m != nil {
		return m.Timewindows
	}
	return nil
}

type Promo_Rule struct {
	RuleId           *int32  `protobuf:"varint,1,req,name=rule_id" json:"rule_id,omitempty"`
	RuleName         *string `protobuf:"bytes,2,req,name=rule_name" json:"rule_name,omitempty"`
	RuleValue        *string `protobuf:"bytes,3,req,name=rule_value" json:"rule_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Promo_Rule) Reset()         { *m = Promo_Rule{} }
func (m *Promo_Rule) String() string { return proto.CompactTextString(m) }
func (*Promo_Rule) ProtoMessage()    {}

func (m *Promo_Rule) GetRuleId() int32 {
	if m != nil && m.RuleId != nil {
		return *m.RuleId
	}
	return 0
}

func (m *Promo_Rule) GetRuleName() string {
	if m != nil && m.RuleName != nil {
		return *m.RuleName
	}
	return ""
}

func (m *Promo_Rule) GetRuleValue() string {
	if m != nil && m.RuleValue != nil {
		return *m.RuleValue
	}
	return ""
}

type Promo_TimeWindow struct {
	TwId             *int32  `protobuf:"varint,1,req,name=tw_id" json:"tw_id,omitempty"`
	TwStart          *string `protobuf:"bytes,2,req,name=tw_start" json:"tw_start,omitempty"`
	TwEnd            *string `protobuf:"bytes,3,req,name=tw_end" json:"tw_end,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Promo_TimeWindow) Reset()         { *m = Promo_TimeWindow{} }
func (m *Promo_TimeWindow) String() string { return proto.CompactTextString(m) }
func (*Promo_TimeWindow) ProtoMessage()    {}

func (m *Promo_TimeWindow) GetTwId() int32 {
	if m != nil && m.TwId != nil {
		return *m.TwId
	}
	return 0
}

func (m *Promo_TimeWindow) GetTwStart() string {
	if m != nil && m.TwStart != nil {
		return *m.TwStart
	}
	return ""
}

func (m *Promo_TimeWindow) GetTwEnd() string {
	if m != nil && m.TwEnd != nil {
		return *m.TwEnd
	}
	return ""
}

func init() {
}
